Remove calorie command
AY2021S1-CS2103T-W11-3/tp pull request #121
Opened 2020-10-23 09:25 UTC by wayne987

remove a certain calorie from a particular day
example: remove tp/out d/2020-10-23 i/2
removes a calorie output from day:2020-10-23 with the index of 2

2020-10-23 10:07 UTC, junhui-phoon requested changes
Add missing Javadocs header to the classes under model/calorie package

2020-10-23 10:07 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/commands/RemoveCommand.java
> +
Javadocs header

2020-10-23 10:07 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/parser/CalorieCommandParser.java
Javadocs header

2020-10-23 10:07 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
> +
Javadocs header

2020-10-23 10:07 UTC, junhui-phoon commented on src/main/java/seedu/address/model/calorie/CalorieManager.java
Javadocs header

2020-10-24 14:26 UTC, ethanso56 commented on src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
> +    private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
add javadocs

2020-10-24 15:23 UTC, ethanso56 commented on src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
> +    private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
for the addPrefixesPresent

2020-10-24 15:59 UTC, ethanso56 reviewed
looks good to me

2020-10-24 16:33 UTC, merged