Storage updates
AY2021S1-CS2103T-W11-3/tp pull request #133
Opened 2020-10-26 21:50 UTC by hoperawr

Test cases aren't finished. Can be merged already though.

2020-10-27 16:20 UTC, hoperawr commented
Can be merged already. Changed equality notion for day to being the same date. Javadoc changes and refactoring.

2020-10-28 04:18 UTC, junhui-phoon approved these changes

2020-10-28 04:37 UTC, junhui-phoon requested changes

2020-10-28 04:37 UTC, junhui-phoon commented on src/test/java/seedu/address/model/day/DayTest.java
> +        assertTrue(DAY1.equals(editedAlice));
actually can just remove these statements, since we don't compare weight and tags

2020-10-28 09:27 UTC, junhui-phoon approved these changes

2020-10-28 09:28 UTC, merged