Change Person class to Day class
AY2021S1-CS2103T-W11-3/tp pull request #47
Opened 2020-10-05 16:18 UTC by ethanso56

changed variable names too

2020-10-06 07:05 UTC, wayne987 commented on LICENSE
> +Permission is hereby granted, free of charge, to any day obtaining a copy
i think the person here is not the same person as the one in the model

2020-10-06 07:43 UTC, ethanso56 commented on LICENSE
> +Permission is hereby granted, free of charge, to any day obtaining a copy
oh ya

2020-10-08 02:12 UTC, junhui-phoon requested changes

2020-10-08 02:12 UTC, junhui-phoon commented on LICENSE
> +copies of the Software, and to permit days to whom the Software is
should be the original persons, this MIT license file no need to edit.

2020-10-08 02:19 UTC, ethanso56 commented on LICENSE
> +copies of the Software, and to permit days to whom the Software is
done

2020-10-08 02:25 UTC, junhui-phoon approved these changes
LGTM

2020-10-08 02:27 UTC, merged