Add calorie manager
AY2021S1-CS2103T-W11-3/tp pull request #85
Opened 2020-10-17 12:08 UTC by wayne987

2020-10-17 14:13 UTC, ethanso56 requested changes

2020-10-17 14:13 UTC, ethanso56 commented on src/test/java/seedu/address/model/day/calorie/CalorieManagerTest.java
> +    void addTotalCalorieOut() {
should this be addTotalCalorieOutput? just like the addTotalCalorieInput() haha

2020-10-17 14:13 UTC, ethanso56 commented on src/main/java/seedu/address/storage/JsonAdaptedDay.java
> +            throw new IllegalValueException(Date.MESSAGE_CONSTRAINTS);
How come this is date? should be calorieManager right?

2020-10-17 14:13 UTC, ethanso56 commented on src/main/java/seedu/address/storage/JsonAdaptedDay.java
> +            throw new IllegalValueException(Date.MESSAGE_CONSTRAINTS);
the Date.MESSAGE_CONSTRAINTS

2020-10-17 14:13 UTC, ethanso56 commented on src/main/java/seedu/address/storage/JsonAdaptedCalorieManager.java
> +     * Converts this Jackson-friendly adapted day object into the model's {@code Day} object.
the javadoc comment should be calorieManager object right? instead of day object

2020-10-17 19:40 UTC, wayne987 commented on src/test/java/seedu/address/model/day/calorie/CalorieManagerTest.java
> +    void addTotalCalorieOut() {
OHH LOL OKOK

2020-10-18 06:20 UTC, ethanso56 commented on src/main/java/seedu/address/logic/commands/CalorieCommand.java
> +            "please add a new day entry for the date intended before adding calorie input/output";
the p want to make it capital P? HAHHAAH

2020-10-19 15:57 UTC, ethanso56 reviewed
looks good to me

2020-10-19 15:59 UTC, merged