Branch profile
AY2021S1-CS2103T-W11-3/tp pull request #94
Opened 2020-10-20 19:41 UTC by jiaax

Refactored AddressBook and its related classes(ABParser and Test) to Person so that is why there's a lot of things changed

2020-10-20 19:48 UTC, junhui-phoon commented
I would recommend that this will be merged last

2020-10-20 20:59 UTC, junhui-phoon requested changes
Good job on the refactoring :)) Try to see and remove any more traces of addressbook, be it code or javadocs
Resolve the merge conflicts.

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/MainApp.java
>              logger.warning("Problem while reading from the file. Will be starting with an empty AddressBook");
need to change the logger message also

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/Logic.java
>      ReadOnlyAddressBook getAddressBook();
is this still supposed to be getAddressBook() or getPerson()? Only the Javadocs header is changed but not the actual code.

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/LogicManager.java
>      public ReadOnlyAddressBook getAddressBook() {
Refactor this method

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/commands/CalorieCommand.java
> +import static seedu.address.logic.parser.CliSyntax.PREFIX_TIME;
hmm now calorie command no need dates?

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/commands/CreateCommand.java
> +
need a Javadocs header here to explain what this class is for.

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/parser/CreateCommandParser.java
> +
javadocs header for the class and the methods, just copy, paste and edit from other existing ones.

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/Model.java
> +    ReadOnlyAddressBook getPerson();
refactor the ReadOnlyAddressBook interface

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/ReadOnlyAddressBook.java
refactor this whole interface class

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/person/Height.java
> +
javadocs header here

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/person/ID.java
> +
javadocs header

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/person/Profile.java
> +
javadocs header

2020-10-20 20:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
>      public static ReadOnlyAddressBook getSampleAddressBook() {
refactor this method

2020-10-21 04:23 UTC, ethanso56 requested changes

2020-10-21 04:23 UTC, ethanso56 commented on src/test/java/seedu/address/model/person/NameTest.java
> +        // null Food
comments should be Name instead of Food

2020-10-21 04:23 UTC, ethanso56 commented on src/test/java/seedu/address/model/person/NameTest.java
> +    public void constructor_invalidFood_throwsIllegalArgumentException() {
test name should be name instead of food

2020-10-21 08:06 UTC, jiaax commented on src/main/java/seedu/address/logic/commands/CalorieCommand.java
> +import static seedu.address.logic.parser.CliSyntax.PREFIX_TIME;
yeah only need time

2020-10-21 13:59 UTC, junhui-phoon requested changes
Paiseh actually AddressBook should be refactored to MyFitnessBuddy. The classes created under model/person/ are fine and these will be the foundation for the Profile feature.

2020-10-21 13:59 UTC, junhui-phoon commented on src/main/java/seedu/address/logic/parser/PersonParser.java
>  import seedu.address.logic.commands.CalorieCommand;
this whole class refactor to MyFitnessBuddyParser

2020-10-21 13:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/Person.java
>  import javafx.collections.ObservableList;
refactor this class to MyFitnessBuddy

2020-10-21 13:59 UTC, junhui-phoon commented on src/main/java/seedu/address/model/ReadOnlyPerson.java
refactor this class to ReadOnlyMyFitnessBuddy

2020-10-22 08:58 UTC, ethanso56 commented on LICENSE
> +Permission is hereby granted, free of charge, to any myFitnessBuddy obtaining a copy
I dont think license need to change haha

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/MainApp.java
> +        Optional<ReadOnlyMyFitnessBuddy> myFitnessBuddyOptionalOptional;
how come this one got 2 optionals

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/MainApp.java
> +            initialData = myFitnessBuddyOptionalOptional.orElseGet(SampleDataUtil::getSampleMyFitnessBuddy);
here also

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/MainApp.java
> +            logger.warning("Data file not in the correct format. Will be starting with a new Person");
this one also shd be myfitnessbuddy

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/MainApp.java
> +            logger.warning("Problem while reading from the file. Will be starting with a new Person");
here also

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/logic/Logic.java
> +     * Returns the Person.
here also haha

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/logic/commands/CreateCommand.java
> + * Creates a profile for the Person.
here is myfitnessbuddy also right?

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/logic/parser/PersonParser.java
> +public class PersonParser {
shd this file be deleted? already got the MyFitnessBuddyPerser liao

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +     * Returns the user prefs' person file path.
myfitnessbuddy?

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +     * Sets the user prefs' person file path.
here also haha

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +    void setMyFitnessBuddyFilePath(Path personFilePath);
myFitnessBuddyFilePath

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +    /** Returns the person */
myFitnessBuddy

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +     * Returns true if a day with the same identity as {@code day} exists in the person.
here also haha

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +     * The day must exist in the person.
here

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +     * {@code day} must not already exist in the person.
here

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/Model.java
> +     * The day identity of {@code editedPerson} must not be the same as another existing day in the person.
here

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/ModelManager.java
> + * Represents the in-memory model of the person data.
here

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/ModelManager.java
> +     * Initializes a ModelManager with the given person and userPrefs.
here

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/ModelManager.java
> +        logger.fine("Initializing with person: " + readOnlyMyFitnessBuddy + " and user prefs " + userPrefs);
here

2020-10-22 08:58 UTC, ethanso56 commented on src/main/java/seedu/address/model/day/Day.java
> + * Represents a Day in the Person.
here

2020-10-22 08:58 UTC, ethanso56 commented on src/test/java/seedu/address/model/ModelManagerTest.java
> +//import java.time.LocalDate;
delete this?

2020-10-22 10:08 UTC, jiaax commented on src/main/java/seedu/address/MainApp.java
> +            initialData = myFitnessBuddyOptionalOptional.orElseGet(SampleDataUtil::getSampleMyFitnessBuddy);
im not changing the storage.readAddressBook cause idk if i should touch the storage class at all haha

2020-10-22 11:30 UTC, junhui-phoon approved these changes
Looks good, hope it doesn't break the app

2020-10-22 11:33 UTC, merged